services:
   web-service:
     depends_on:
       - model-service
     image: mosazhaw/djl-serving-consumer:latest
     ports:
       - "80:8082"
     restart: always

   model-service:
     image: mosazhaw/djl-serving:latest
     ports:
       - "8080:8080"
     restart: always
