services:
   web-service:
     depends_on:
       - model-service
     # use a tag if caching problems on azure occur with the latest tag  
     image: mosazhaw/djl-serving-consumer:latest
     ports:
       - "80:8082"
     restart: always

   model-service:
     # use a tag if caching problems on azure occur with the latest tag  
     image: mosazhaw/djl-serving:latest
     restart: always
